[workspace]
resolver = "3"
members = ["domain", "application", "adapters", "server", "test-support"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"
publish = false

[workspace.dependencies]
domain = { path = "domain" }
application = { path = "application" }
adapters = { path = "adapters" }
test-support = { path = "test-support" }
