[package]
name = "server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
application.workspace = true
domain.workspace = true
adapters.workspace = true

[dev-dependencies]
test-support.workspace = true
